hl.on("hyprland.start", function ()
    hl.exec_cmd("sunsetr & waybar & swaync & hypridle")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("hyprctl setcursor Miku Cursor 24")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)